<?xml version="1.0"?>
<robot name="furbot" 
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- PARAMETERS SETTINGS: INERTIA OF ALL KIND OF GEOMETRY OBJECT -->

    <macro name="cylinder_inertia" params="m r h">
        <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}" />
    </macro>

    <macro name="box_inertia" params="m x y z">
        <inertia ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0" iyy="${m*(x*x+z*z)/12}" iyz = "0" izz="${m*(x*x+z*z)/12}" />
    </macro>

    <macro name="sphere_inertia" params="m r">
        <inertia ixx="${2*m*r*r/5}" ixy = "0" ixz = "0" iyy="${2*m*r*r/5}" iyz = "0" izz="${2*m*r*r/5}" />
    </macro>

    <!-- REAR WHEEL MACROS -->

    <macro name="rear_wheel" params="lr tY">

        <link name="${lr}_rear_wheel">
            <collision>
                <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
                <geometry>
                    <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
                <geometry>
                    <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
                </geometry>
                <material name="black"/>
            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
                <mass value="${wheelMass}"/>
                <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
            </inertial>
        </link>

        <gazebo reference="${lr}_rear_wheel">
            <material>Gazebo/Black</material>
        </gazebo>

        <joint name="${lr}_rear_wheel_hinge" type="continuous">
            <parent link="chassis"/>
            <child link="${lr}_rear_wheel"/>
            <origin xyz="${-wheelPos+chassisLength/2} ${tY*wheelWidth/2+tY*0.01+tY*chassisWidth/2} ${wheelRadius}" rpy="0 0 0" />
            <axis xyz="0 1 0" rpy="0 0 0" />
            <limit effort="100" velocity="100"/>
            <joint_properties damping="0.0" friction="0.0"/>
        </joint>

        <transmission name="${lr}_rear_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${lr}_rear_wheel_hinge">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${lr}_rear_Motor">
                <mechanicalReduction>10</mechanicalReduction>
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </actuator>
        </transmission>

    </macro>

    <!-- FRONT WHEEL MACRO -->

    <macro name="front_wheel" params="lr tY">

        <link name="${lr}_front_wheel">
            <collision>
                <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
                <geometry>
                    <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
                <geometry>
                    <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
                </geometry>
                <material name="black"/>
            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
                <mass value="${wheelMass}"/>
                <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
            </inertial>
        </link>

        <gazebo reference="${lr}_front_wheel">
            <material>Gazebo/Black</material>
        </gazebo>

        <link name="${lr}_steer">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.06 0.06 0.06" />
                </geometry>
            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="1"/>
                <box_inertia m="1" x="0.06" y="0.06" z="0.06"/>
            </inertial>

        </link>

        <gazebo reference="${lr}_steer">
            <material>Gazebo/Black</material>
        </gazebo>

        <joint name="${lr}_steer_joint" type="revolute">
            <origin xyz="${wheelPos-chassisLength/2}  ${tY*wheelWidth/2+tY*0.01+tY*chassisWidth/2}  ${wheelRadius}" rpy="0.0 0.0 0.0"/>
            <parent link="chassis"/>
            <child link="${lr}_steer"/>
            <axis xyz="0 0 1"/>
            <limit lower="-1" upper="1" effort="100" velocity="100"/>
        </joint>>

        <joint name="${lr}_front_wheel_hinge" type="continuous">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <parent link="${lr}_steer" />
            <child link="${lr}_front_wheel" />
            <axis xyz="0 1 0" />
            <limit effort="100" velocity="100" />
        </joint>


        <transmission name="${lr}_front_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${lr}_steer_joint">
                <hardwareInterface>hardware_interface/PositionJointInterface </hardwareInterface>
            </joint>
            <actuator name="${lr}_front_Motor">
                <mechanicalReduction>10</mechanicalReduction>
                <hardwareInterface>hardware_interface/PositionJointInterface </hardwareInterface>
            </actuator>
        </transmission>

    </macro>

    <!-- CASTOR WHEELS MACRO -->

    <macro name="front_castor_wheel">
        <joint name="fixed" type="fixed">
            <parent link="chassis"/>
            <child link="castor_wheel"/>
        </joint>

        <link name="castor_wheel">
            <collision>
                <origin xyz="${chassisLength/2-casterRadius} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${casterRadius}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="${chassisLength/2-casterRadius} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${casterRadius}"/>
                </geometry>
                <material name="red"/>
            </visual>

            <inertial>
                <origin xyz="${chassisLength/2-casterRadius} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
                <mass value="${casterMass}"/>
                <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
            </inertial>
        </link>
    </macro>
</robot>