obstacle_range: 1.5
raytrace_range: 3.0
inflation_radius: 0.25
observation_sources: laser_scan_sensor 
laser_scan_sensor: {sensor_frame: footprint, data_type: LaserScan, topic: /furbot/laser/scan, marking: true, clearing: true}

