
footprint: [ [-0.15,-0.28], [0.65,-0.28], [0.65,0.28], [-0.15,0.28] ]

transform_tolerance: 0.5
map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 3.5
 raytrace_range: 3.5
 inflation_radius: 0.1
 track_unknown_space: false
 combination_method: 1
 observation_sources: laser_scan_sensor
 laser_scan_sensor: {sensor_frame: footprint, data_type: LaserScan, topic: /furbot/laser_scan, marking: true, clearing: true}

inflation_layer:
  enabled:              true
  cost_scaling_factor:  10  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.1  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "/map"
