<?xml version="1.0"?>
<robot name="mybot" 
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="PI" value="3.1415926535897931"/>

    <xacro:property name="chassisHeight" value="0.1"/>
    <xacro:property name="chassisLength" value="0.6"/>
    <xacro:property name="chassisWidth" value="0.2"/>
    <xacro:property name="chassisMass" value="50"/>

    <xacro:property name="casterRadius" value="0.05"/>
    <xacro:property name="casterMass" value="5"/>

    <xacro:property name="wheelWidth" value="0.05"/>
    <xacro:property name="wheelRadius" value="0.08"/>
    <xacro:property name="wheelPos" value="0.45"/>
    <xacro:property name="wheelMass" value="5"/>

    <xacro:property name="cameraSize" value="0.05"/>
    <xacro:property name="cameraMass" value="0.1"/>


    <xacro:include filename="$(find mybot_description)/urdf/mybot.gazebo" />
    <xacro:include filename="$(find mybot_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find mybot_description)/urdf/macros.xacro" />

    <link name='chassis'>
        <collision>
            <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <inertial>
            <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
            <mass value="${chassisMass}"/>
            <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
        </inertial>
    </link>

    <link name="footprint" />

    <joint name="base_joint" type="fixed">
        <parent link="footprint"/>
        <child link="chassis"/>
    </joint>

    <rear_wheel lr="right" tY="-1" />
    <rear_wheel lr="left" tY="1" />

    <front_wheel lr="right" tY="-1" />
    <front_wheel lr="left" tY="1" />

    <link name="camera">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <inertial>
            <mass value="${cameraMass}" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
        </inertial>
    </link>

    <joint name="camera_joint" type="fixed">
        <origin xyz="${chassisLength/2} 0 ${chassisHeight}" rpy="0.0 0.0 0.0"/>
        <parent link="chassis"/>
        <child link="camera"/>
    </joint>

    <link name="base_laser_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.05 0.05 0.05" />
            </geometry>
            <material name="green" />
        </visual>
        <inertial>
            <mass value="0.000001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
        </inertial>
    </link>

    <joint name="laser" type="fixed">
        <origin xyz="${chassisLength/2} 0 ${chassisHeight+0.001}" rpy="0 0 0" />
        <parent link="chassis" />
        <child link="base_laser_link" />
    </joint>

</robot>